services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_USER_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db
    volumes:
      - .:/home/app/web
    command: >
      sh -c "python manage.py migrate &&
             gunicorn edu_platform.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
    ports:
      - "5433:5432"

volumes:
  postgres_data: 